# # Form implementation generated from reading ui file 'MainWindow.ui'
# #
# # Created by: PyQt6 UI code generator 6.7.1
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic6 is
# # run again.  Do not edit this file unless you know what you are doing.
#
#
# from PyQt6 import QtCore, QtGui, QtWidgets
#
#
# class Ui_MainWindow(object):
#     def setupUi(self, MainWindow):
#         MainWindow.setObjectName("MainWindow")
#         MainWindow.resize(583, 511)
#         self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
#         self.centralwidget.setObjectName("centralwidget")
#         self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
#         self.gridLayoutWidget.setGeometry(QtCore.QRect(90, 30, 371, 401))
#         self.gridLayoutWidget.setObjectName("gridLayoutWidget")
#         self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
#         self.gridLayout.setContentsMargins(0, 0, 0, 0)
#         self.gridLayout.setObjectName("gridLayout")
#         self.widget = QtWidgets.QWidget(parent=self.gridLayoutWidget)
#         self.widget.setObjectName("widget")
#         self.Home = QtWidgets.QPushButton(parent=self.widget)
#         self.Home.setGeometry(QtCore.QRect(0, 0, 141, 81))
#         self.Home.setObjectName("Home")
#         self.Roles = QtWidgets.QPushButton(parent=self.widget)
#         self.Roles.setGeometry(QtCore.QRect(0, 80, 141, 81))
#         self.Roles.setObjectName("Roles")
#         self.Custom = QtWidgets.QPushButton(parent=self.widget)
#         self.Custom.setGeometry(QtCore.QRect(0, 160, 141, 81))
#         self.Custom.setObjectName("Custom")
#         self.Pipeline = QtWidgets.QPushButton(parent=self.widget)
#         self.Pipeline.setGeometry(QtCore.QRect(0, 240, 141, 81))
#         self.Pipeline.setObjectName("Pipeline")
#         self.Arbitration = QtWidgets.QPushButton(parent=self.widget)
#         self.Arbitration.setGeometry(QtCore.QRect(0, 320, 141, 81))
#         self.Arbitration.setObjectName("Arbitration")
#         self.ChatBotDisplay = QtWidgets.QWidget(parent=self.widget)
#         self.ChatBotDisplay.setGeometry(QtCore.QRect(140, 0, 231, 401))
#         self.ChatBotDisplay.setObjectName("ChatBotDisplay")
#         self.label = QtWidgets.QLabel(parent=self.ChatBotDisplay)
#         self.label.setGeometry(QtCore.QRect(90, 30, 54, 12))
#         self.label.setObjectName("label")
#         self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
#         MainWindow.setCentralWidget(self.centralwidget)
#         self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
#         self.menubar.setGeometry(QtCore.QRect(0, 0, 583, 22))
#         self.menubar.setObjectName("menubar")
#         MainWindow.setMenuBar(self.menubar)
#         self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
#         self.statusbar.setObjectName("statusbar")
#         MainWindow.setStatusBar(self.statusbar)
#
#         self.retranslateUi(MainWindow)
#         QtCore.QMetaObject.connectSlotsByName(MainWindow)
#
#     def retranslateUi(self, MainWindow):
#         _translate = QtCore.QCoreApplication.translate
#         MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
#         self.Home.setText(_translate("MainWindow", "Home"))
#         self.Roles.setText(_translate("MainWindow", "Roles"))
#         self.Custom.setText(_translate("MainWindow", "Custom"))
#         self.Pipeline.setText(_translate("MainWindow", "Pipeline"))
#         self.Arbitration.setText(_translate("MainWindow", "Arbitration"))
#         self.label.setText(_translate("MainWindow", "Chat Bot"))
#
#
# from PyQt5.QtWidgets import (
#     QApplication, QMainWindow, QWidget, QVBoxLayout, QHBoxLayout,
#     QLabel, QLineEdit, QPushButton, QStackedWidget
# )
# import sys
#
#
# class ArbitrationPage(QWidget):
#     def __init__(self):
#         super().__init__()
#
#         # 主垂直布局
#         main_layout = QVBoxLayout(self)
#
#         # 顶部控件区域
#         top_layout = QHBoxLayout()
#         # 左侧按钮
#         left_button = QPushButton()
#         left_button.setFixedSize(50, 30)
#         mid_left_button = QPushButton()
#         mid_left_button.setFixedSize(50, 30)
#
#         # 中间 Arbitration 标题
#         title_label = QLabel("Arbitration")
#         title_label.setAlignment(Qt.AlignCenter)
#
#         # 右侧按钮
#         mid_right_button = QPushButton()
#         mid_right_button.setFixedSize(50, 30)
#         right_button = QPushButton()
#         right_button.setFixedSize(50, 30)
#
#         # 将按钮和标题添加到顶部布局
#         top_layout.addWidget(left_button)
#         top_layout.addWidget(mid_left_button)
#         top_layout.addWidget(title_label)
#         top_layout.addWidget(mid_right_button)
#         top_layout.addWidget(right_button)
#
#         main_layout.addLayout(top_layout)
#
#         # 四个输入区域
#         for i in range(1, 5):
#             prompt_layout = QHBoxLayout()
#             prompt_label = QLabel(f"Prompt-{i}")
#             prompt_input = QLineEdit()
#             prompt_input.setPlaceholderText("Input box")
#             prompt_layout.addWidget(prompt_label)
#             prompt_layout.addWidget(prompt_input)
#             main_layout.addLayout(prompt_layout)
#
#         # Enter按钮
#         enter_button = QPushButton("Enter")
#         enter_button.setFixedSize(60, 30)
#         main_layout.addWidget(enter_button, alignment=Qt.AlignRight)
#
#
# class MainWindow(QMainWindow):
#     def __init__(self):
#         super().__init__()
#         self.setWindowTitle("Arbitration Layout Example")
#
#         # 主窗口布局
#         central_widget = QWidget()
#         self.setCentralWidget(central_widget)
#         main_layout = QHBoxLayout(central_widget)
#
#         # 左侧菜单栏
#         menu_layout = QVBoxLayout()
#         buttons = ["Home", "Roles", "Custom", "Pipeline", "Arbitration"]
#         for name in buttons:
#             btn = QPushButton(name)
#             btn.setFixedSize(100, 60)
#             menu_layout.addWidget(btn)
#
#         main_layout.addLayout(menu_layout)
#
#         # 中间页面区域
#         self.stacked_widget = QStackedWidget()
#         self.arbitration_page = ArbitrationPage()
#         self.stacked_widget.addWidget(self.arbitration_page)
#
#         main_layout.addWidget(self.stacked_widget)
#
#
# if __name__ == "__main__":
#     app = QApplication(sys.argv)
#     window = MainWindow()
#     window.show()
#     sys.exit(app.exec_())

from PyQt6.QtWidgets import (
    QApplication, QMainWindow, QWidget, QVBoxLayout, QHBoxLayout,
    QLabel, QLineEdit, QPushButton, QStackedWidget
)
from PyQt6.QtCore import Qt
import sys


class ArbitrationPage(QWidget):
    def __init__(self):
        super().__init__()

        # 主垂直布局
        main_layout = QVBoxLayout(self)

        # 顶部控件区域
        top_layout = QHBoxLayout()
        # 左侧按钮
        left_button = QPushButton()
        left_button.setFixedSize(50, 30)
        mid_left_button = QPushButton()
        mid_left_button.setFixedSize(50, 30)

        # 中间 Arbitration 标题
        title_label = QLabel("Arbitration")
        title_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        # 右侧按钮
        mid_right_button = QPushButton()
        mid_right_button.setFixedSize(50, 30)
        right_button = QPushButton()
        right_button.setFixedSize(50, 30)

        # 将按钮和标题添加到顶部布局
        top_layout.addWidget(left_button)
        top_layout.addWidget(mid_left_button)
        top_layout.addWidget(title_label)
        top_layout.addWidget(mid_right_button)
        top_layout.addWidget(right_button)

        main_layout.addLayout(top_layout)

        # 四个输入区域
        for i in range(1, 5):
            prompt_layout = QHBoxLayout()
            prompt_label = QLabel(f"Prompt-{i}")
            prompt_input = QLineEdit()
            prompt_input.setPlaceholderText("Input box")
            prompt_layout.addWidget(prompt_label)
            prompt_layout.addWidget(prompt_input)
            main_layout.addLayout(prompt_layout)

        # Enter按钮
        enter_button = QPushButton("Enter")
        enter_button.setFixedSize(60, 30)
        main_layout.addWidget(enter_button, alignment=Qt.AlignmentFlag.AlignRight)


class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Arbitration Layout Example")

        # 主窗口布局
        central_widget = QWidget()
        self.setCentralWidget(central_widget)
        main_layout = QHBoxLayout(central_widget)

        # 左侧菜单栏
        menu_layout = QVBoxLayout()
        buttons = ["Home", "Roles", "Custom", "Pipeline", "Arbitration"]
        for name in buttons:
            btn = QPushButton(name)
            btn.setFixedSize(100, 60)
            menu_layout.addWidget(btn)

        main_layout.addLayout(menu_layout)

        # 中间页面区域
        self.stacked_widget = QStackedWidget()
        self.arbitration_page = ArbitrationPage()
        self.stacked_widget.addWidget(self.arbitration_page)

        main_layout.addWidget(self.stacked_widget)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())
