# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1212, 852)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(101, 60, 141, 401))
        self.widget.setObjectName("widget")
        self.Home = QtWidgets.QPushButton(parent=self.widget)
        self.Home.setGeometry(QtCore.QRect(0, 0, 141, 81))
        self.Home.setObjectName("Home")
        self.Roles = QtWidgets.QPushButton(parent=self.widget)
        self.Roles.setGeometry(QtCore.QRect(0, 80, 141, 81))
        self.Roles.setObjectName("Roles")
        self.Custom = QtWidgets.QPushButton(parent=self.widget)
        self.Custom.setGeometry(QtCore.QRect(0, 160, 141, 81))
        self.Custom.setObjectName("Custom")
        self.Pipeline = QtWidgets.QPushButton(parent=self.widget)
        self.Pipeline.setGeometry(QtCore.QRect(0, 240, 141, 81))
        self.Pipeline.setObjectName("Pipeline")
        self.Arbitration = QtWidgets.QPushButton(parent=self.widget)
        self.Arbitration.setGeometry(QtCore.QRect(0, 320, 141, 81))
        self.Arbitration.setObjectName("Arbitration")
        self.ChatBotDisplay = QtWidgets.QWidget(parent=self.centralwidget)
        self.ChatBotDisplay.setGeometry(QtCore.QRect(241, 60, 391, 401))
        self.ChatBotDisplay.setObjectName("ChatBotDisplay")
        self.label = QtWidgets.QLabel(parent=self.ChatBotDisplay)
        self.label.setGeometry(QtCore.QRect(160, 30, 54, 12))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1212, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Home.setText(_translate("MainWindow", "Home"))
        self.Roles.setText(_translate("MainWindow", "Roles"))
        self.Custom.setText(_translate("MainWindow", "Custom"))
        self.Pipeline.setText(_translate("MainWindow", "Pipeline"))
        self.Arbitration.setText(_translate("MainWindow", "Arbitration"))
        self.label.setText(_translate("MainWindow", "Chat Bot"))
